name: Docker build

on:
  workflow_dispatch:
  push:
    branches: ["dev", "main"]
    tags: ["v*"]

permissions:
  contents: read
  packages: write

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Google Container Registry
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Extract Docker metadata
        id: meta
        uses: crazy-max/ghaction-docker-meta@v5
        with:
          images: gcr.io/xplor-2025/spiderfoot
          tags: |
            type=ref,event=branch
            type=sha
          flavor: |
            latest=auto

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Show image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
