name: Tests

on:
  push:
    branches: [ "main", "dev", "master" ]
  pull_request:
    branches: [ "main", "dev", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-xdist pytest-cov
          if [ -f test/requirements.txt ]; then pip install -r test/requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics

      - name: Test with pytest
        env:
          PYTEST_ADDOPTS: -q
        run: |
          python -m pytest -n auto --dist loadfile --ignore=test/integration/modules/ --durations=5 --cov-report=term --cov=. .
